{
  "sksl": "// This SkSL shader is autogenerated by spirv-cross.\n\nfloat4 flutter_FragCoord;\n\nuniform vec2 resolution;\nuniform float time;\nuniform vec2 mouse;\n\nvec4 fragColor;\n\nvec3 flutterBlue;\nvec3 flutterNavy;\nvec3 flutterSky;\n\nvec2 FLT_flutter_local_FlutterFragCoord()\n{\n    return flutter_FragCoord.xy;\n}\n\nvoid FLT_main()\n{\n    flutterBlue = vec3(0.01960784383118152618408203125, 0.3254902064800262451171875, 0.69411766529083251953125);\n    flutterNavy = vec3(0.01568627543747425079345703125, 0.16862745583057403564453125, 0.3490196168422698974609375);\n    flutterSky = vec3(0.007843137718737125396728515625, 0.4901960790157318115234375, 0.99215686321258544921875);\n    vec2 uv = FLT_flutter_local_FlutterFragCoord() / resolution;\n    vec2 center = vec2(0.5);\n    uv.x *= (resolution.x / resolution.y);\n    float center_dist = distance(uv, center);\n    float RADIUS = 0.119999997317790985107421875 + (0.0199999995529651641845703125 * sin(time / 1000000.0));\n    float alpha = float(center_dist < RADIUS);\n    fragColor = vec4(alpha, sin(time / 10000000.0), alpha, 1.0);\n}\n\nhalf4 main(float2 iFragCoord)\n{\n      flutter_FragCoord = float4(iFragCoord, 0, 0);\n      FLT_main();\n      return fragColor;\n}\n",
  "stage": 1,
  "target_platform": 2,
  "uniforms": [
    {
      "array_elements": 0,
      "bit_width": 32,
      "columns": 1,
      "location": 0,
      "name": "resolution",
      "rows": 2,
      "type": 10
    },
    {
      "array_elements": 0,
      "bit_width": 32,
      "columns": 1,
      "location": 1,
      "name": "time",
      "rows": 1,
      "type": 10
    },
    {
      "array_elements": 0,
      "bit_width": 32,
      "columns": 1,
      "location": 2,
      "name": "mouse",
      "rows": 2,
      "type": 10
    }
  ]
}